### ISSUE TITLE
Default values for mandatory fields

### ISSUE THREAD

**Issue by tensau** [roidayan/redmine.js#28]
It would be very convinient, if some the mandatory fields on the "New Ticket" dialog would be pre-filled:
status -> "new" (or lowest status in workflow)
priority -> "normal"
assignee -> project owner

**Comment by roidayan** [comment]
some redmine hosting services have project setting for default assignee. so use that.

**Comment by roidayan** [comment]
priority and assignee have default value when querying redmine api but not assignee. from the service I check if it is left blank then the default is being used. so for assignee i'll remove the requirement.
